const oportunidades = [
	
	
		{
	id: 1,
	titulo: "Postulación UWC Paraguay 2027–2029",
	organizacion: "UWC Paraguay",
	categoria: "Becas",
	edad: "Consultar criterios de elegibilidad",
	elegibilidad: "Estudiantes paraguayos que cumplan con los criterios de elegibilidad de UWC Paraguay para la convocatoria 2027–2029.",
	requisitos: "Completar la postulación en línea, presentar información académica y extracurricular, responder las preguntas y ensayos requeridos, presentar referencias y documentos solicitados, y contar con permiso de padre, madre o tutor legal.",
	beneficios: "Oportunidad de estudiar en uno de los colegios UWC durante el período 2027–2029. La plaza puede contar con financiamiento total o parcial según la necesidad económica demostrada.",
	costo: "Consultar convocatoria oficial",
	modalidad: "Presencial",
	ubicacion: "Colegio UWC asignado internacionalmente",
	fechaLimite: "27 de noviembre de 2026",
	fechaLimiteISO: "2026-11-27",
	descripcion: "Proceso de selección de UWC Paraguay para estudiantes que buscan realizar una experiencia educativa internacional en los Colegios del Mundo Unido durante el período 2027–2029.",
	enlace: "https://py.uwc.org/como-aplicar/"
},
	
	{
	id: 2,
	titulo: "Premio Emprendedor del Año 2026",
	organizacion: "Premio Emprendedor del Año",
	categoria: "Concursos",
	edad: "18 años o más",
	elegibilidad: "Personas de 18 años o más con un emprendimiento lícito radicado en Paraguay o con una idea incluida en las categorías habilitadas. La categoría Emprendimiento Juvenil está dirigida a jóvenes de 18 a 29 años.",
	requisitos: "Completar el formulario y perfil del emprendimiento. Se requiere cédula vigente y, según la categoría y situación del emprendimiento, RUC u otra documentación establecida en las bases.",
	beneficios: "Participación en un programa de fortalecimiento, evaluación y posibilidad de obtener reconocimiento y premios según la categoría.",
	costo: "Gratuito",
	modalidad: "Online",
	ubicacion: "Paraguay",
	fechaLimite: "11 de octubre de 2026",
	fechaLimiteISO: "2026-10-11",
	descripcion: "Convocatoria nacional que busca reconocer, visibilizar e impulsar emprendimientos paraguayos. Cuenta con una categoría específica para emprendimientos liderados por jóvenes de 18 a 29 años.",
	enlace: "https://premioemprendedor.com.py/"
},

	{
		id: 4,
		titulo: "BRAVA Awards 2026–2027",
		organizacion: "Fundación BRAVA",
		categoria: "Concursos",
		edad: "19 a 30 años",
		elegibilidad: "Artistas emergentes de 19 a 30 años, de cualquier nacionalidad o lugar de residencia, que se encuentren desarrollando activamente su práctica artística.",
		requisitos: "Presentar una obra pictórica y completar la postulación digital de acuerdo con las bases de la convocatoria.",
		beneficios: "Premios estímulo de hasta USD 5.000, posibilidad de acceder a residencias artísticas internacionales de ocho semanas y exhibición de las obras ganadoras.",
		costo: "Gratuito",
		modalidad: "Online",
		ubicacion: "Internacional",
		fechaLimite: "27 de octubre de 2026",
		fechaLimiteISO: "2026-10-27",
		descripcion: "Convocatoria internacional para jóvenes artistas emergentes dedicada al lenguaje pictórico, creada para descubrir nuevos talentos y generar oportunidades para el desarrollo de sus carreras.",
		enlace: "https://fundacionbrava.org/noticias/open-call"
	},
	{
		id: 5,
		titulo: "Escuela de Formación Política para Mujeres Líderes – XVII Edición",
		organizacion: "Justicia Electoral",
		categoria: "Capacitaciones",
		edad: "Consultar convocatoria oficial",
		elegibilidad: "Mujeres líderes residentes en Asunción interesadas en fortalecer sus conocimientos y capacidades de liderazgo y participación política.",
		requisitos: "Completar el formulario de inscripción y cumplir con los criterios establecidos por la Justicia Electoral.",
		beneficios: "Formación gratuita en democracia, participación política, derechos humanos, políticas públicas, comunicación, campañas electorales y otros temas relacionados con liderazgo político.",
		costo: "Gratuito",
		modalidad: "Presencial",
		ubicacion: "Asunción, Paraguay",
		fechaLimite: "14 de octubre de 2026",
		fechaLimiteISO: "2026-10-14",
		descripcion: "Programa de formación de dos meses que busca fortalecer el liderazgo y empoderamiento político de mujeres mediante conocimientos conceptuales, herramientas prácticas e intercambio de experiencias.",
		enlace: "https://tsje.gov.py/noticias/leer/12035-inscripciones-abiertas-a-nueva-edicion-de-la-escuela-de-formacion-politica-para-mujeres-lideres----en-asuncion.html"
	},
	{
		id: 6,
		titulo: "Programa de Becas de Cooperación Sur-Sur – República de Chile 2027",
		organizacion: "AGCID – Gobierno de Chile",
		categoria: "Becas",
		edad: "Profesionales",
		elegibilidad: "Profesionales nacionales de países elegibles de América Latina y el Caribe, incluido Paraguay, que cumplan los requisitos de admisión del programa de Magíster seleccionado.",
		requisitos: "Contar con aceptación definitiva e incondicional de una institución chilena participante y presentar la documentación académica, profesional y administrativa requerida.",
		beneficios: "Financiamiento de matrícula, arancel y titulación, manutención mensual, seguro para programas presenciales, materiales y apoyo para tesis según las condiciones de la convocatoria.",
		costo: "Gratuito",
		modalidad: "Presencial, híbrida o virtual según el programa",
		ubicacion: "Chile",
		fechaLimite: "20 de octubre de 2026, 15:00 h",
		fechaLimiteISO: "2026-10-20",
		descripcion: "Programa de becas para profesionales de América Latina y el Caribe que quieran cursar estudios de Magíster en universidades e instituciones de educación superior chilenas acreditadas.",
		enlace: "https://becas.mef.gov.py/cooperacion/beca/datalle251/activo"
	},
	{
		id: 7,
		titulo: "Robótica VEX – Curso 82084",
		organizacion: "SNPP",
		categoria: "Capacitaciones",
		edad: "Desde 15 años",
		elegibilidad: "Personas desde los 15 años interesadas en aprender sobre diseño, construcción y programación de robots.",
		requisitos: "Registrarse en el portal del SNPP y realizar la inscripción al curso utilizando el código 82084. Los cupos son limitados.",
		beneficios: "Capacitación gratuita en robótica, utilizando herramientas y kits para desarrollar conocimientos de ensamblaje, programación, sensores y resolución de problemas.",
		costo: "Gratuito",
		modalidad: "Presencial",
		ubicacion: "Sede central del SNPP, Asunción",
		fechaLimite: "Hasta agotar cupos",
		fechaLimiteISO: null,
		descripcion: "Curso presencial de Robótica VEX orientado a personas desde los 15 años. Las clases incluyen diseño, construcción y programación de robots.",
		enlace: "https://www.snpp.edu.py/"
	}
];
