const oportunidades = [
	{
		id: 1,
		titulo: "Olimpiada de Informática Aguarandu – Bebras 2026",
		organizacion: "OMAPA",
		categoria: "Concursos",
		edad: "Según curso y liga",
		elegibilidad: "Estudiantes de 4.º a 6.º grado de EEB, 7.º a 9.º grado de EEB y 1.º a 3.º curso de Educación Media, según la liga correspondiente.",
		requisitos: "Participar en dupla o de forma individual (la participación individual cuenta como dupla) y registrarse previamente. Las ligas Gigabyte y Terabyte incluyen programación; Kilobyte y Megabyte no incluyen programación.",
		beneficios: "Participación en una competencia nacional de pensamiento computacional e informática, posibilidad de clasificar a la fase final y medallas de Oro, Plata y Bronce por liga.",
		costo: "G. 80.000 por dupla. Gratuito para estudiantes de instituciones públicas y privadas subvencionadas de todo el país, gracias al apoyo de CONACYT.",
		modalidad: "Virtual en la fase inicial y presencial en la fase final",
		ubicacion: "Paraguay. La fase final se realiza en sedes habilitadas por OMAPA; Gigabyte y Terabyte tienen sede en Asunción/Central.",
		fechaLimite: "Consultar convocatoria oficial",
		fechaLimiteISO: null,
		descripcion: "Olimpiada de informática y pensamiento computacional en la que estudiantes resuelven desafíos de lógica, pensamiento computacional y, según la liga, tareas de programación. En 2026 OMAPA se integra oficialmente a la comunidad internacional Bebras.",
		enlace: "https://www.omapa.org/proyectos/aguarandu/"
	},
	{
		id: 2,
		titulo: "Desafío Jóvenes con Ideas (ejemplo ficticio)",
		organizacion: "Red Juvenil Imaginaria",
		categoria: "Concursos",
		edad: "15 a 25 años",
		elegibilidad: "Jóvenes paraguayos",
		requisitos: "Presentar una idea original y completar el formulario de inscripción ficticio.",
		beneficios: "Reconocimiento ficticio, mentoría y oportunidad de presentar el proyecto ante otras personas jóvenes.",
		costo: "Gratuito",
		modalidad: "Online",
		ubicacion: "Desde cualquier lugar",
		fechaLimite: "15 de noviembre de 2099",
		fechaLimiteISO: "2099-11-15",
		descripcion: "Concurso ficticio para presentar ideas creativas que ayuden a transformar la comunidad.",
		enlace: "#"
	},
	{
		id: 3,
		titulo: "Curso de Habilidades del Futuro (ejemplo ficticio)",
		organizacion: "Academia Virtual Inventada",
		categoria: "Capacitaciones",
		edad: "16 a 30 años",
		elegibilidad: "Jóvenes paraguayos interesados en capacitarse",
		requisitos: "Tener acceso a internet y compromiso para completar las actividades del curso.",
		beneficios: "Acceso a contenidos ficticios, certificado de participación y desarrollo de nuevas habilidades.",
		costo: "Gratuito",
		modalidad: "Online",
		ubicacion: "Desde cualquier lugar",
		fechaLimite: "4 de septiembre de 2020",
		fechaLimiteISO: "2020-09-04",
		descripcion: "Capacitación ficticia para desarrollar habilidades útiles para el estudio y el trabajo.",
		enlace: "#"
	},
    {
		id: 4,
    	titulo: "Taller de Introducción a la Programación (ejemplo ficticio)",
    	organizacion: "Centro de Innovación Juvenil",
    	categoria: "Capacitaciones",
		edad: "15 a 25 años",
		elegibilidad: "Jóvenes de 15 a 25 años residentes en Paraguay",
		requisitos: "Tener interés en aprender programación y acceso a una computadora con internet.",
		beneficios: "Prácticas guiadas, materiales de aprendizaje y certificado ficticio de finalización.",
    	costo: "Sin costo",
    	modalidad: "Online",
    	ubicacion: "Desde cualquier lugar",
    	fechaLimite: "20 de noviembre de 2099",
		fechaLimiteISO: "2099-11-20",
    	descripcion: "Taller ficticio para jóvenes interesados en aprender los fundamentos de la programación.",
    	enlace: "#"
    },
    {
		id: 5,
		titulo: "Democrakit 2026",
		organizacion: "Alma Cívica",
		categoria: "Capacitaciones",
		edad: "18 a 35 años",
		elegibilidad: "Jóvenes de 18 a 35 años que formen parte de un equipo de 3 a 5 integrantes y quieran desarrollar soluciones para fortalecer la democracia y generar impacto en sus comunidades.",
		requisitos: "Postularse en equipos de 3 a 5 jóvenes y cumplir con los criterios establecidos en la convocatoria oficial.",
		costo: "Gratuito",
		modalidad: "Consultar convocatoria oficial",
		ubicacion: "Paraguay",
		fechaLimite: "20 de septiembre de 2026",
		fechaLimiteISO: "2026-09-20",
		beneficios: "Formación cívica, mentoría personalizada y acompañamiento para desarrollar soluciones comunitarias con impacto territorial.",
		descripcion: "Programa juvenil de Alma Cívica que busca potenciar la participación de jóvenes mediante formación, mentoría y el desarrollo de soluciones para fortalecer la democracia a nivel local.",
		enlace: "https://almacivica.org/alma-civica-convoca-a-grupos-juveniles-para-potenciar-la-democracia-local/"
    }
];
